In [1]:
import numpy as np 
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, explained_variance_score, confusion_matrix, accuracy_score, classification_report, log_loss
from math import sqrt

In [3]:
raw_data=pd.read_csv('Q3_train.csv')
print(raw_data.shape)

raw_data.head(5)

(31, 6)


Date    DAU  Installs  Uninstalls  Signups  Referrals
0  2022-10-01  24071      6630        6994     3511        962
1  2022-10-02  23548      6366        6669     3387        941
2  2022-10-03  24572      6936        6899     3654        940
3  2022-10-04  24212      6561        6766     3532        960
4  2022-10-05  23247      6059        6402     3315        923

In [10]:
X = raw_data.drop(['Date','Referrals'],axis=1).values
X = X.astype(int)
X

Y = raw_data['Referrals']
Y = Y.astype(int)
Y

0      962
1      941
2      940
3      960
4      923
5      822
6      957
7      994
8     1016
9     1186
10    1161
11    1193
12     987
13     860
14     772
15    1052
16     801
17     572
18     606
19     700
20     512
21     530
22     484
23     384
24     435
25     491
26     551
27     555
28     536
29     573
30     419
Name: Referrals, dtype: int32

In [34]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.85, test_size=0.15)
log_reg = LogisticRegression(random_state=15)

log_reg.fit(X_train, Y_train)


C:\Users\abraa\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=15)

In [35]:
log_reg.predict(X_train)
y_pred = log_reg.predict(X_train)
print(y_pred)

[ 555  551  384  962  923  860  801  941  536 1193  772 1186  994  530
  573  484  572 1016  491  419  435 1052  960  940  987  512]


In [36]:
# Accuracy on Train
print("The Training Accuracy is: ", log_reg.score(X_train, Y_train))


# Classification Report
print(classification_report(Y_train, y_pred))

The Training Accuracy is:  1.0
              precision    recall  f1-score   support

         384       1.00      1.00      1.00         1
         419       1.00      1.00      1.00         1
         435       1.00      1.00      1.00         1
         484       1.00      1.00      1.00         1
         491       1.00      1.00      1.00         1
         512       1.00      1.00      1.00         1
         530       1.00      1.00      1.00         1
         536       1.00      1.00      1.00         1
         551       1.00      1.00      1.00         1
         555       1.00      1.00      1.00         1
         572       1.00      1.00      1.00         1
         573       1.00      1.00      1.00         1
         772       1.00      1.00      1.00         1
         801       1.00      1.00      1.00         1
         860       1.00      1.00      1.00         1
         923       1.00      1.00      1.00         1
         940       1.00      1.00      1.00       

In [47]:
#Predict referrals
predict_data = pd.read_csv('Q3_predict.csv')
predict_data = predict_data.drop(['Date','Referrals'],axis=1).values
predict_data = predict_data.astype(int)
pred = log_reg.predict(predict_data)
print(predict_data)
pred





[[12816  3763  4149  1806]
 [12812  3087  3868  1550]
 [12042  3176  3815  1410]
 [12595  3172  3878  1629]
 [12361  3390  4021  1578]
 [13166  3441  4071  1656]
 [12565  3468  4011  1556]
 [12988  4468  4143  1808]
 [12992  4491  4638  2017]
 [13377  4261  4480  1997]
 [13826  4274  4512  2047]
 [13464  4660  4856  2066]
 [13415  4416  4749  2147]
 [13873  4097  4305  2065]
 [14459  4890  4593  2707]]


array([ 536,  530,  435,  551,  435,  555,  491,  860, 1016,  860,  536,
       1016,  860,  801, 1193])